name: Build TheHive

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

#      - uses: actions/setup-node@v3
#        with:
#          node-version: lts/hydrogen

      - name: Curl 
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash

      - name: Build
        run: |
          export NVM_DIR="${HOME}/.nvm" 
          . "$NVM_DIR/nvm.sh"
          nvm --lts
          npm install -g bower grunt
          ls -la
          ./sbt stage
